### ISSUE TITLE
Disconnect Label 

### ISSUE THREAD

**Issue by pwigger** [Kennox/rscc#138] opened 2017-05-18 13:53 UTC
Back button closes the connection: should be labelled appropriate

**Comment by pwigger** [comment] 2017-05-21 18:46
If a VNC connection is going on, once you click the back button, the Connection is ended. 
This is not clear to the user: Either way: an ongoing connection disables the back button, but a "End connection"-Button is showed instead or the back button is named end Vnc support (or likewise) if a VNC session is ongoing.

**Comment by Gyssim** [comment] 2017-05-25 08:49
make back button which is labeled with close connection

**Comment by Gyssim** [comment] 2017-05-25 08:50
request view

**Comment by Gyssim** [comment] 2017-05-27 13:25
@martinfrancois ready to merge

**Comment by l-marchesi** [comment] 2017-05-28 15:51
fixed with #167

**Comment by rmosimann** [comment] 2017-06-06 11:57
Still missing to disable the BackButton when connected.

**Comment by martinfrancois** [comment] 2017-06-15 11:48
duplicate of #181

**Closed as completed by martinfrancois** 2017-06-15 11:48 UTC
